<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>59cb20db-02f1-44ee-a80b-63d3f027f733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3cfc1e0a-ce36-490d-a09b-09305f46864c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b938969-7409-48b3-a465-4b13268c9b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>210.0</value>
      <webElementGuid>4d0cada7-8027-4d14-b343-a7cb561e0345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7e35f269-4a1e-4210-8096-74a8e7628c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.</value>
      <webElementGuid>a1a1037b-6687-463e-9bff-96334d3fd04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.</value>
      <webElementGuid>43deef98-791b-4c22-899f-781ed521e995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.</value>
      <webElementGuid>6d58745a-49ef-47f4-bbd1-c06eb5e281f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>478.0</value>
      <webElementGuid>f0a1d166-ed2b-49d7-93a3-45af6248b0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>154.0</value>
      <webElementGuid>a8d90fc0-370a-4d19-aed4-fcaf8b5ad924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>506.0</value>
      <webElementGuid>ed6751c1-7471-49f6-8f10-2bc9ce5af8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[17]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>c4fb5919-70a0-454a-9f12-615b29ed7081</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' and @name = 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' and @value = 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.']</locator>
   <locatorCollection>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' AND name == 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' AND name == 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.'</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' and @name = 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' and @value = 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[17]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' AND name == 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.' AND value == 'When you share your location with this app, a blue location indicator will appear to view your current position on the map. This will help you to locate nearby assets of your facility.'`]</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
