<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authorize</name>
   <tag></tag>
   <elementGuidId>5d6b5063-68f4-4421-a929-68c8b821f46d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'notify.authorize()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;notify\.authorize\(\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Authorize&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4c554af-2ea1-4e18-b5fd-e15e1031914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>notify.authorize()</value>
      <webElementGuid>6c7baf45-788b-4c9d-a8e3-ca7e1cc1e18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize</value>
      <webElementGuid>88dd1f67-a35e-4fbf-8f70-9dc581e50a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Authorize</value>
      <webElementGuid>d1f56d4d-9fbc-4f47-856c-6fd3644749ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-20af880359b2186f0d9598b7c83378e7</value>
      <webElementGuid>1e647f05-e591-4cc6-9507-078d96296ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'notify.authorize()']</value>
      <webElementGuid>01faa318-163d-465e-88b0-85c11418f6b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'notify.authorize()']</value>
      <webElementGuid>927ca532-3eec-49b5-8379-76fc6e102d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Authorize' or . = 'Authorize')]</value>
      <webElementGuid>8c6fddf4-a2f4-4cf8-94ec-befa54c80f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
